### ISSUE TITLE
package.json does not have the correct version

### ISSUE THREAD

**Issue by RA80533** [moreeyesplz/meep_scanner#2]
According to the repository page, the most recent release is tagged as [v1.0.2](https://github.com/moreeyesplz/meep_scanner/tree/v1.0.2). The package.json manifest incorrectly versions the project at 1.0.0:

https://github.com/moreeyesplz/meep_scanner/blob/14f68038f59387d218a9a4bc0be3b0de7fcc47cd/package.json#L3

**Comment by jeremyong** [comment]
Thanks, we'll fix it on the next release

**Comment by jeremyong** [comment]
Fixed!
